version: "3.9"
services:
  form-builder-be:
    build: .
    container_name: form-builder-be
    environment:
      - DB_USER=dennyrezky
      - DB_PASSWORD=
      - DB_HOST=host.docker.internal
      - DB_NAME=form_builder
      - DB_SSL_MODE=disable
      - PORT=8087
      - REDIS_SERVER_NETWORK=redisserver:6379
      - REDIS_SERVER_PASSWORD=
    ports:
      - "8087:8087"
    depends_on:
      - redisserver
  redisserver:
    image: redis:6.2.11
    container_name: redisserver
    ports:
      - "127.0.0.1:6379:6379"
  nginx:
    image: nginx:1.23.3
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - form-builder-be
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - nginx_log_form_builder_be:/var/log/nginx/


volumes:
  nginx_log_form_builder_be:
    driver: local